language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

branches:
    only:
        - /^v\d\.\d/

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer install --no-interaction

script:
  - composer run test

after_script:
  - php vendor/bin/coveralls -v

sudo: false
